### ISSUE TITLE
Could you give me the MMDPlugin.lib?

### ISSUE THREAD

**Issue by ray-cast** [oigami/EffekseerForMMD#12]
Hi.
I would like to compile your project, but i can't find MMDPlugin.lib file.
so, could you give me the MMDPlugin.lib? 
Thanks.

**Comment by oigami** [comment]
It is contained in a [MMDPlugin_v0.11.zip](https://github.com/oigami/EffekseerForMMD/releases/tag/v0.11)

I will add a description about how to compile it.

**Comment by ray-cast** [comment]
I have successfully compiled it, thank you for this effect.
