### ISSUE TITLE
バグ報告　

### ISSUE THREAD

**Issue by ghost** [oigami/EffekseerForMMD#19]
指示された通りEffekseerForMMD を導入したのですが、MMD上でうまく表示されません。
ファイルは一応読み込めるのですが、再生されたときにエフェクトが出てきません。

**Comment by oigami** [comment]
どのようなキーフレームで試しましたか？できればvmdファイルを添付してください

**Comment by ghost** [comment]
情報を追加します。OSはWindows１０でMMDは64ビットの最新版、EffekseerForMMD は確かV２．０
だったと思います。efkファイルはEffekseerのサイトにあったものをダウンロードして解凍したフォルダと
同じ位置に置いたのでテクスチャが読まれていないという線は薄いと思います。
vmdファイル、pmmファイルも添付しておきます。
[Files.zip](https://github.com/oigami/EffekseerForMMD/files/629434/Files.zip)

**Comment by oigami** [comment]
おそらく再生ボーンのy座標が常に7だからです。effekseerのツールで7フレームのときに何か表示されているか確認してください。
